name: Testes e RelatÃ³rios

on: [push, pull_request] # Executa nos commits e PRs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: ğŸ—ï¸ Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: ğŸ“¦ Restaurar pacotes
        run: dotnet restore

      - name: âœ… Executar Testes UnitÃ¡rios (xUnit)
        run: |
          dotnet test src/snacktech-api-products.sln --logger "trx;LogFileName=TestResults.trx" --collect:"XPlat Code Coverage" 

      - name: ğŸ“Š Gerar RelatÃ³rio de Cobertura (xUnit)
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:**/coverage.cobertura.xml -targetdir:TestResults -reporttypes:Html

      - name: ğŸ—ï¸ Instalar SpecFlow LivingDoc
        run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

      - name: ğŸ“‘ Gerar RelatÃ³rio BDD (SpecFlow)
        run: |
          livingdoc test-assembly **/*.dll --test-execution TestResults.trx

      - name: ğŸš€ Publicar RelatÃ³rios no GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./TestResults
